name: Export Secret Scanning Alerts to CSV

on:
  workflow_dispatch: # So you can manually trigger it when needed

jobs:
  fetch-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch Secret Scanning Alerts and Save to CSV
        env:
          ORG_NAME: ${{ github.repository_owner }} 
        run: |
          echo "Fetching secret scanning alerts..."

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ghp_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/$ORG_NAME/secret-scanning/alerts" > alerts.json

          echo "Parsing JSON to CSV..."

          # Build the CSV header
          echo "alert_number,repository,secret_type,state,created_at,resolved_at" > alerts.csv

          # Parse each alert entry
          jq -r '.[] | [
            .number, 
            .repository.full_name, 
            .secret_type, 
            .state, 
            .created_at, 
            (.resolved_at // "")
          ] | @csv' alerts.json >> alerts.csv

          echo "CSV file generated: alerts.csv"

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret-scanning-alerts
          path: alerts.csv
